### ISSUE TITLE
Lax parsing of Cargo-flavored SPDX

### ISSUE THREAD

**Issue by kornelski** [EmbarkStudios/spdx#18]
Cargo/crates-io is not strict about SPDX syntax, so it allows crates with licenses such as "MIT/Apache". 

Currently this crate parses SPDX strictly, so many "Cargo-flavored" can't be parsed.

Would you be interested in expanding the parser to be more relaxed about the syntax and allow `/` as a synonym for `OR` and fix incomplete SPDX identifiers?

**Comment by Jake-Shadle** [comment]
I think it makes sense due to cargo's behavior, though if I recall correctly, it doesn't allow `/` in newly published crates at least. Since the expression parser always keeps its own copy of the original expression, it should be easy to correct malformed expressions before starting the parse like we do eg [here](https://github.com/EmbarkStudios/cargo-deny/blob/010c1baf4bcc8c974905c46dcf42906537f95e96/src/lib.rs#L202-L208)

**Comment by Jake-Shadle** [comment]
Quick follow up, as noted in #21 I accidentally released this change as a patch even though the minimum rust version was increased due to the use of `#[non_exhaustive]`, so I've published a new version without `#[non_exhaustive]` and yanked 0.3.1, I hope that's ok!
