### ISSUE TITLE
Failed to parse license code GFDL-1.1-invariants-or-later

### ISSUE THREAD

**Issue by metaswitch-colin-haywood** [EmbarkStudios/spdx#39]
**Describe the bug**
License code `GFDL-1.1-invariants-or-later` fails to parse

**To Reproduce**
Trying to parse license string `GPL-3.0-or-later AND GFDL-1.1-invariants-or-later`, the following error is encountered:

```
thread 'main' panicked at 'Unable to find root GNU license', <...>/spdx-0.4.1/src/lib.rs:259:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1321:5
   3: <spdx::LicenseReq as core::convert::From<spdx::LicenseId>>::from
   4: spdx::expression::parser::<impl spdx::expression::Expression>::parse_mode
   5: spdx::expression::parser::<impl spdx::expression::Expression>::parse
   6: <calling code>
```

**Expected behavior**
`GFDL-1.1-invariants-or-later` is a valid SPDX code so should be parsed OK.

**Device:**
 - OS: Ubuntu (docker container) 18.04

**Additional context**
Problem appears to be that the code raising that error in `lib.rs` strips off the `-or-later` and expects the result to be a valid SPDX code, but `GFDL-1.1-invariants` by itself is not a valid SPDX code. So this may need a special case of a special case :-)

**Comment by Jake-Shadle** [comment]
I've gone with a similar approach to the other GNU licenses for the GFDL ones, basically

1. `GFDL-<version>` is the same as `GFDL-<version>-no-invariants`
2. `GFDL-<version>-invariants` is considered a modifier on the base license, kind of like license exceptions, but different, because GNU, so `GFDL-1.2-invariants != GFDL-1.2`
3. `-only` and `-or-later` are otherwise treated the same as the other GNU licenses, ie, ignored by license requirements for the purposes of matching, and not allowed by `Licensee::parse`
