### ISSUE TITLE
Simplify `ParseError`

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/spdx#45]
`ParseError` is currently complicated with a lifetime which makes it annoying to consume, and it also means that a successful parsing _always_ heap allocates a clone of the original input, even if on the caller's side they already have an owned string that they actually aren't going to use after parsing anyways.

**Comment by hoijui** [comment]
I am facing the same issue right now. Instead of using `thiserror`'s convenient `#[from] spdx::ParseError`, I have to .. basically copy the struct into my enum error, replace the `&'a str` with `String`, implement a `From<spdx::ParseError>` for my error enum, the reverse `From` as well, so I can use it in the `Display` impl of my error struct. All in all, almost 40 lines of code.
I asked a few questions regarding this in the rust chat on discord, and the verdict is clear: definitely no dynamic data in an error (if borrowed, only with a `'static` lifetime). I would therefore suggest to use `String` there.

---

For the same reason (and others), I would wrap [this error]:

```rust
pub fn evaluate_with_failures<AF: FnMut(&LicenseReq) -> bool>(
        &self,
        mut allow_func: AF,
    ) -> Result<(), Vec<&ExpressionReq>> {
```

(the `Vec<&ExpressionReq>` part)
into a struct.

With your approval, I could prepare a PR for those two changes.

**Comment by Jake-Shadle** [comment]
The first one is fine to take a stab at, but `evaluate_with_failures` is specifically meant for building your own error context/log output etc at the callsite based on the application's needs, so that one should not be changed.

**Comment by hoijui** [comment]
hmm... 
the way I would want to do that (for `evaluate_with_failures`), would be to wrap its error with a `thiserror`, and implement `Display` for it, either with `thiserror`s `#[error("...")]`, or with an explicit `impl Display for MyError`. For that purpose though, it would be much better if it would return `Vec<ExpressionReq>` instead of `Vec<&ExpressionReq>`, and still better if it returned a proper error type (implementing `std::error::Error` and `Debug` I think, were the requirements for that).
That still allows to write custom display code for the wrapping error on the caller side.
Or say: using non-static references dictates, that the error data either:
* has to be manually deep cloned before it can be passed out pf the scope where it was raised in, or
* has to be handled completely (e.g. by `print!`ing) in that scope
That is what the current `Vec<&ExpressionReq>` return type dictates, and while I am just a newb in rust, I got feedback from three seasoned rust devs, that this is bad practice -> errors should be fully owned or static refs.

**Comment by Jake-Shadle** [comment]
> That is what the current Vec<&ExpressionReq> return type dictates, and while I am just a newb in rust, I got feedback from three seasoned rust devs, that this is bad practice -> errors should be fully owned or static refs.

Yes, this is generally good practice, but this applies to normal case of returning errors in a chain, this method is _not_ meant for that, it is meant for diagnostic reporting or other specific cases. It's quite easy for external code to consume a `Vec<&ExpressionReq>` via `From<>` for their error type and transform it your specific application error if you like, I just don't think it makes sense to do it in this library.

**Comment by hoijui** [comment]
well...
this is the minimum I came up with:

```
/// An owned/no-lifetimes transcription of `Vec<&spdx::expression::ExpressionReq>`
#[derive(thiserror::Error, Debug)]
pub struct ApprovementFailure {
    /// The list of expresions that were not approved
    pub failed: Vec<spdx::expression::ExpressionReq>,
}

impl From<Vec<&spdx::expression::ExpressionReq>> for ApprovementFailure {
    fn from(err: Vec<&spdx::expression::ExpressionReq>) -> Self {
        Self {
            failed: err.iter().map(|req| req.to_owned().clone()).collect(),
        }
    }
}

impl fmt::Display for ApprovementFailure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_fmt(format_args!("{:?}", self.failed))
    }
}
```

I need this extra code just for one function call, and it does not even include code for pretty printing. imagine I needed that much code for every function I need to call from an other crate.
Happy to get shown how I could get rid of this.

**Comment by Jake-Shadle** [comment]
Well, I don't want `evaluate_with_failures` changed for the reasons I've already stated, but feel free to add another method like `evaluate_with_error` that just returns a `std::error::Error` implementation that does the same thing you just posted. Please don't use `thiserror`, there is no reason to add a new dependency for this.

**Comment by hoijui** [comment]
I also tried to wrap the `Vec<ExpressionReq>` into an error struct, but then figured that [`std::error::Error::source()`](https://doc.rust-lang.org/std/error/trait.Error.html#method.source)can only return one error, and which one would that be, if there is more then one?
.. so.. makes little sense, or say.. it would somewhat hide all but one error in some scenarios.
I am sure you knew all this/figured it out long ago already, and then did not remember the exact details why it does not make sense now.... well, as you said: no good solution for that, so what there is now, is probably the best.
